create table public.promotions (
    id bigint generated by default as identity primary key,
    slug text not null,
    title text not null,
    subtitle text not null default '',
    description text not null default '',
    category text not null,
    validity_label text not null,
    image_path text,
    href text not null default '#',
    status text not null default 'active',
    is_featured boolean not null default false,
    is_disabled boolean not null default false,
    sort_order integer not null default 50,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint promotions_slug_format check (
        slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
    ),
    constraint promotions_title_length check (
        char_length(title) between 2 and 100
    ),
    constraint promotions_subtitle_length check (
        char_length(subtitle) <= 140
    ),
    constraint promotions_description_length check (
        char_length(description) <= 500
    ),
    constraint promotions_category_length check (
        char_length(category) between 1 and 60
    ),
    constraint promotions_validity_length check (
        char_length(validity_label) between 1 and 100
    ),
    constraint promotions_status_value check (
        status in ('active', 'upcoming', 'ended')
    ),
    constraint promotions_sort_order_range check (
        sort_order between 0 and 9999
    )
);

create unique index promotions_slug_unique
on public.promotions (lower(slug));

create index promotions_public_order_idx
on public.promotions (is_active, sort_order, id);

alter table public.promotions enable row level security;

revoke all on table public.promotions from anon, authenticated;
grant select on table public.promotions to anon, authenticated;
grant all on table public.promotions to service_role;
grant usage, select on sequence public.promotions_id_seq to service_role;

create policy "Public can view active promotions"
on public.promotions
for select
to anon, authenticated
using (is_active = true);

insert into public.promotions (
    slug,
    title,
    subtitle,
    description,
    category,
    validity_label,
    href,
    status,
    is_featured,
    is_disabled,
    sort_order
)
values
    (
        'welcome-reward',
        'Welcome Reward',
        'Exclusive New Member Package',
        'New members can enjoy a premium welcome reward after completing the required registration steps.',
        'New Member',
        'Limited-time campaign',
        '#',
        'active',
        true,
        false,
        10
    ),
    (
        'weekly-cashback',
        'Weekly Cashback',
        'Rewards Every Week',
        'Eligible members can enjoy weekly cashback rewards based on the applicable campaign requirements.',
        'Cashback',
        'Available weekly',
        '#',
        'active',
        false,
        false,
        20
    ),
    (
        'vip-upgrade',
        'VIP Upgrade',
        'Unlock Premium Membership Benefits',
        'Upgrade your membership level and unlock additional rewards, priority support and exclusive privileges.',
        'VIP',
        'Ongoing',
        '#',
        'active',
        true,
        false,
        30
    ),
    (
        'referral-reward',
        'Referral Reward',
        'Invite Friends and Earn Rewards',
        'Invite eligible friends to join and receive rewards when the campaign requirements are completed.',
        'Referral',
        'Limited-time campaign',
        '#',
        'upcoming',
        false,
        false,
        40
    ),
    (
        'birthday-reward',
        'Birthday Reward',
        'A Special Reward for Your Celebration',
        'Eligible members may receive a special birthday reward during their birthday month.',
        'Member Reward',
        'Birthday month',
        '#',
        'active',
        false,
        false,
        50
    ),
    (
        'seasonal-campaign',
        'Seasonal Campaign',
        'Limited Seasonal Benefits',
        'Enjoy selected seasonal rewards and special campaign benefits during the promotional period.',
        'Seasonal',
        'Campaign ended',
        '#',
        'ended',
        false,
        true,
        60
    );

insert into storage.buckets (
    id,
    name,
    public,
    file_size_limit,
    allowed_mime_types
)
values (
    'promotion-images',
    'promotion-images',
    true,
    2097152,
    array[
        'image/png',
        'image/jpeg',
        'image/webp'
    ]
)
on conflict (id) do update
set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;
