create table public.downloads (
    id bigint generated by default as identity primary key,
    slug text not null,
    title text not null,
    description text not null default '',
    logo_path text not null,
    platform text not null,
    version text not null default 'Latest',
    release_date date not null default current_date,
    file_size text not null default 'Check download',
    download_url text not null default '#',
    guide_url text,
    is_latest boolean not null default true,
    is_disabled boolean not null default false,
    sort_order integer not null default 50,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint downloads_slug_format check (
        slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
    ),
    constraint downloads_title_length check (
        char_length(title) between 2 and 80
    ),
    constraint downloads_description_length check (
        char_length(description) <= 300
    ),
    constraint downloads_platform_value check (
        platform in ('android', 'ios', 'windows')
    ),
    constraint downloads_version_length check (
        char_length(version) between 1 and 40
    ),
    constraint downloads_file_size_length check (
        char_length(file_size) between 1 and 40
    ),
    constraint downloads_sort_order_range check (
        sort_order between 0 and 9999
    )
);

create unique index downloads_slug_unique
on public.downloads (lower(slug));

create index downloads_public_order_idx
on public.downloads (is_active, platform, sort_order, id);

alter table public.downloads enable row level security;

revoke all on table public.downloads from anon, authenticated;
grant select on table public.downloads to anon, authenticated;
grant all on table public.downloads to service_role;
grant usage, select on sequence public.downloads_id_seq to service_role;

create policy "Public can view active downloads"
on public.downloads
for select
to anon, authenticated
using (is_active = true);

insert into public.downloads (
    slug,
    title,
    description,
    logo_path,
    platform,
    version,
    release_date,
    file_size,
    download_url,
    guide_url,
    is_latest,
    sort_order
)
values
    (
        'mega888-android',
        'Mega888',
        'Download the latest official Mega888 application for Android devices.',
        '/games/mega888.png',
        'android',
        'Latest',
        '2026-07-30',
        'Check download',
        '#',
        '#installation-guide',
        true,
        10
    ),
    (
        'pussy888-android',
        'Pussy888',
        'Download the official Pussy888 application with a smooth mobile experience.',
        '/games/pussy888.png',
        'android',
        'Latest',
        '2026-07-30',
        'Check download',
        '#',
        '#installation-guide',
        true,
        20
    ),
    (
        '918kiss-android',
        '918Kiss',
        'Get the latest official 918Kiss application for Android devices.',
        '/games/918kiss.png',
        'android',
        'Latest',
        '2026-07-30',
        'Check download',
        '#',
        '#installation-guide',
        true,
        30
    ),
    (
        '918kaya-android',
        '918Kaya',
        'Download the latest official 918Kaya mobile application.',
        '/games/918kaya.png',
        'android',
        'Latest',
        '2026-07-30',
        'Check download',
        '#',
        '#installation-guide',
        true,
        40
    ),
    (
        'evo888-android',
        'Evo888',
        'Access the latest official Evo888 application for Android.',
        '/games/evo888.png',
        'android',
        'Latest',
        '2026-07-30',
        'Check download',
        '#',
        '#installation-guide',
        true,
        50
    ),
    (
        'newtown-android',
        'Newtown',
        'Download the latest Newtown mobile application for Android devices.',
        '/games/newtown.png',
        'android',
        'Latest',
        '2026-07-30',
        'Check download',
        '#',
        '#installation-guide',
        true,
        60
    );

insert into storage.buckets (
    id,
    name,
    public,
    file_size_limit,
    allowed_mime_types
)
values (
    'download-logos',
    'download-logos',
    true,
    2097152,
    array[
        'image/png',
        'image/jpeg',
        'image/webp'
    ]
)
on conflict (id) do update
set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;
