create table public.brands (
    id bigint generated by default as identity primary key,
    name text not null check (char_length(name) between 2 and 80),
    description text not null default '' check (char_length(description) <= 300),
    rating numeric(2, 1) not null default 5.0 check (rating between 1.0 and 5.0),
    whatsapp_url text not null default '#',
    heylink_url text not null default '#',
    logo_path text not null check (char_length(logo_path) between 1 and 500),
    sort_order integer not null default 0 check (sort_order between 0 and 9999),
    is_active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create unique index brands_name_unique
on public.brands (lower(name));

create index brands_public_order_idx
on public.brands (is_active, sort_order, id);

alter table public.brands enable row level security;

revoke all on table public.brands from anon, authenticated;
grant select on table public.brands to anon, authenticated;
grant all on table public.brands to service_role;
grant usage, select on sequence public.brands_id_seq to service_role;

create policy "Public can view active brands"
on public.brands
for select
to anon, authenticated
using (is_active = true);

insert into public.brands (
    name,
    description,
    rating,
    whatsapp_url,
    heylink_url,
    logo_path,
    sort_order,
    is_active
)
values
    (
        '7ERA Club',
        'Premium gaming membership platform.',
        5.0,
        '#',
        '#',
        '/brands/7era.png',
        10,
        true
    ),
    (
        'SC Club',
        'VIP rewards and campaign management.',
        5.0,
        '#',
        '#',
        '/brands/scclub.png',
        20,
        true
    ),
    (
        'TNG30',
        'Fast access to exclusive promotions.',
        5.0,
        '#',
        '#',
        '/brands/tng30.png',
        30,
        true
    ),
    (
        'ShopPay',
        'Integrated payment and membership.',
        5.0,
        '#',
        '#',
        '/brands/shoppay.png',
        40,
        true
    );
