create table public.games (
    id bigint generated by default as identity primary key,
    slug text not null,
    name text not null,
    description text not null default '',
    logo_path text not null,
    download_url text not null default '#',
    rating numeric(2, 1) not null default 5.0,
    sort_order integer not null default 50,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint games_slug_format check (
        slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
    ),
    constraint games_name_length check (
        char_length(name) between 2 and 80
    ),
    constraint games_description_length check (
        char_length(description) <= 300
    ),
    constraint games_rating_range check (
        rating between 1 and 5
    ),
    constraint games_sort_order_range check (
        sort_order between 0 and 9999
    )
);

create unique index games_slug_unique
on public.games (lower(slug));

create unique index games_name_unique
on public.games (lower(name));

create index games_public_order_idx
on public.games (is_active, sort_order, id);

alter table public.games enable row level security;

revoke all on table public.games from anon, authenticated;
grant select on table public.games to anon, authenticated;
grant all on table public.games to service_role;
grant usage, select on sequence public.games_id_seq to service_role;

create policy "Public can view active games"
on public.games
for select
to anon, authenticated
using (is_active = true);

insert into public.games (
    slug,
    name,
    description,
    logo_path,
    download_url,
    rating,
    sort_order
)
values
    (
        'mega888',
        'Mega888',
        'A smooth and popular mobile gaming experience.',
        '/games/mega888.png',
        '#',
        5.0,
        10
    ),
    (
        '918kiss',
        '918Kiss',
        'Popular mobile games with exciting entertainment options.',
        '/games/918kiss.png',
        '#',
        5.0,
        20
    ),
    (
        '918kaya',
        '918Kaya',
        'Premium mobile entertainment with rewarding experiences.',
        '/games/918kaya.png',
        '#',
        5.0,
        30
    ),
    (
        'pussy888',
        'Pussy888',
        'Classic mobile games with smooth and reliable performance.',
        '/games/pussy888.png',
        '#',
        5.0,
        40
    ),
    (
        'evo888',
        'Evo888',
        'A trusted platform designed for seamless mobile gameplay.',
        '/games/evo888.png',
        '#',
        5.0,
        50
    ),
    (
        'newtown',
        'Newtown',
        'Modern mobile entertainment with premium content.',
        '/games/newtown.png',
        '#',
        5.0,
        60
    );

insert into storage.buckets (
    id,
    name,
    public,
    file_size_limit,
    allowed_mime_types
)
values (
    'game-logos',
    'game-logos',
    true,
    2097152,
    array[
        'image/png',
        'image/jpeg',
        'image/webp'
    ]
)
on conflict (id) do update
set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;
