create table public.faq_items (
    id bigint generated by default as identity primary key,
    slug text not null,
    category text not null,
    question text not null,
    answer text not null,
    sort_order integer not null default 50,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint faq_items_slug_format check (
        slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
        and char_length(slug) <= 100
    ),
    constraint faq_items_category_check check (
        category in ('download', 'promotion', 'account', 'technical', 'security')
    ),
    constraint faq_items_question_length check (
        char_length(question) between 5 and 200
    ),
    constraint faq_items_answer_length check (
        char_length(answer) between 5 and 2000
    ),
    constraint faq_items_sort_order_check check (
        sort_order between 0 and 9999
    )
);

create unique index faq_items_slug_key on public.faq_items (slug);
create index faq_items_public_order_idx
    on public.faq_items (sort_order, id)
    where is_active = true;

alter table public.faq_items enable row level security;

revoke all on table public.faq_items from anon, authenticated;
grant select on table public.faq_items to anon, authenticated;
grant select, insert, update, delete on table public.faq_items to service_role;
grant usage, select on sequence public.faq_items_id_seq to service_role;

create policy "Public can read active FAQ items"
    on public.faq_items
    for select
    to anon, authenticated
    using (is_active = true);

insert into public.faq_items (
    slug,
    category,
    question,
    answer,
    sort_order
)
values
    (
        'download-install',
        'download',
        'How do I install the application?',
        'Download the latest application from the Download Center and follow the installation guide provided on the page.',
        1
    ),
    (
        'download-update',
        'download',
        'How do I update my application?',
        'Simply download the latest version and install it over your existing application.',
        2
    ),
    (
        'promotion-claim',
        'promotion',
        'How do I claim a promotion?',
        'Open the Promotions page and follow the campaign requirements before contacting customer support if needed.',
        3
    ),
    (
        'account-register',
        'account',
        'How do I create an account?',
        'Contact our official customer support team to begin the registration process.',
        4
    ),
    (
        'technical-app',
        'technical',
        'The application won''t open. What should I do?',
        'Restart your device, install the latest version and ensure your internet connection is stable.',
        5
    ),
    (
        'security-safe',
        'security',
        'How do I know the download is safe?',
        'Only download applications from the official 7ERA Platform Download Center.',
        6
    );
